version: "3.9"
services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: smartges
      MB_DB_PORT: 5432
      MB_DB_USER: _018491f3d322be13
      MB_DB_PASS: _6090d166135e750be362ac8f1352f2
      MB_DB_HOST: primary.smartges-metabase-db--6k9vlsyv7ksg.addon.code.run
    networks:
      - metanet1
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
networks:
  metanet1:
    driver: bridge
